In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns #for beatiful visualizations
%matplotlib inline 
import scipy.stats as scs #for statistics
import operator
from scipy.stats import chi2_contingency
import matplotlib.ticker as ticker
pd.set_option('display.notebook_repr_html', True)
def _repr_latex_(self):
    return "\centering{%s}" % self.to_latex()

pd.DataFrame._repr_latex_ = _repr_latex_

In [9]:
dataset = pd.read_csv("../dataset/ResultDataset.csv",index_col='Unnamed: 0')

In [11]:
dataset_version2 = pd.read_csv("../dataset/ResultDatasetBeta.csv",index_col='Unnamed: 0')

In [16]:
dataset.to_latex("../../FinalYearProjectReport/text/error.tex",bold_rows=True,decimal=',',encoding='utf-8',escape=True,index=False)

In [17]:
dataset_version2.to_latex("../../FinalYearProjectReport/text/error2.tex",bold_rows=True,decimal=',',index=False,encoding='utf-8',escape=True)

In [10]:
dataset.head(1)

Faculte Dimensions       MODEL    RMSE Train     CVSCORE Mean  CVSCORE Std  \
0                     ElasticNet  0.05 : 9.51%  0.069  : 12.25%       0.0046   

        RMSE Test STACK_RES  
0  0.07 : 12.089%

In [6]:
data=[('00987772', 'AB123' ),
('00987772', 'AB123' ),
('00987772', 'AB123' ),
('00987772', 'ED245' ),
('00982123', 'GH564' )]


In [11]:
ID= []
Bank_account = []

In [12]:
for x in data :
    ID.append(x[0])
    Bank_account.append(x[1])

In [14]:
ID = np.array(ID)

In [15]:
Bank_account = np.array(Bank_account)

In [16]:
ID

array(['00987772', '00987772', '00987772', '00987772', '00982123'], 
      dtype='|S8')

In [17]:
Bank_account

array(['AB123', 'AB123', 'AB123', 'ED245', 'GH564'], 
      dtype='|S5')

In [18]:
y_data =[
('AB123','High'),
('ED245' , 'Low'),
('GH564' , 'Low')]

In [19]:
ID_y = []
label =[]
for x in y_data:
    ID_y.append(x[0])
    label.append(x[1])

['AB123', 'ED245', 'GH564']

In [23]:
x_data= pd.DataFrame(index=Bank_account, data=ID, columns=['Bank_Num'])

In [24]:
y_data = pd.DataFrame(index=ID_y, data=label , columns=['label'])

In [26]:
y_data.reset_index(inplace=True)

In [28]:
x_data.reset_index(inplace=True)

In [29]:
x_data


index  Bank_Num
0  AB123  00987772
1  AB123  00987772
2  AB123  00987772
3  ED245  00987772
4  GH564  00982123

In [32]:
dataset=pd.merge(left=x_data, right=y_data, on='index')

In [31]:
from sklearn.model_selection import train_test_split

In [35]:
dataset['Bank_Num'] = dataset.Bank_Num.astype(np.float128)

In [2]:
from sklearn.preprocessing import LabelEncoder,LabelBinarizer

In [38]:
le = LabelEncoder()

In [40]:
le = LabelEncoder()
dataset['index'] = le.fit_transform(dataset.index)

index  Bank_Num label
0      0  987772.0  High
1      1  987772.0  High
2      2  987772.0  High
3      3  987772.0   Low
4      4  982123.0   Low

In [45]:
lb = LabelBinarizer()
dataset['label'] = lb.fit_transform(dataset.label)

In [49]:
dataset.set_index(keys='index', inplace=True)

In [51]:
dataset.reset_index(inplace=True)

In [54]:
x = dataset[['index','Bank_Num']]

In [56]:
X_train, X_test, y_train, y_test = train_test_split(dataset[['index','Bank_Num']], dataset.label, test_size=0.25, random_state=42)

In [57]:
X_train

index  Bank_Num
2      2  987772.0
0      0  987772.0
3      3  987772.0

In [59]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
index       5 non-null int64
Bank_Num    5 non-null float128
label       5 non-null int64
dtypes: float128(1), int64(2)
memory usage: 232.0 bytes


In [60]:
from sklearn.svm import SVC 

In [61]:
clf = SVC(gamma=0.001, C=100., probability=True)

In [62]:
clf.fit(X_train, y_train)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [63]:
clf.predict(X_test)

array([0, 0])

In [64]:
dataset['Bank_Num'] = lb.fit_transform(dataset.Bank_Num)

In [65]:
dataset

index  Bank_Num  label
0      0         1      0
1      1         1      0
2      2         1      0
3      3         1      1
4      4         0      1

In [35]:
dataset = pd.DataFrame({'menu': [['Italian', 'Greek'], ['Japanese'], ['Italian','Greek', 'Japanese']], 'price': ['$$', '$$', '$'], 'location': [['NY', 'CA','MI'], 'CA', ['NY', 'CA','MA']]})

In [4]:
dataset

location                        menu price
0  [NY, CA, MI]            [Italian, Greek]    $$
1            CA                  [Japanese]    $$
2  [NY, CA, MA]  [Italian, Greek, Japanese]     $

In [42]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = LabelBinarizer()

In [43]:
location =[]
encoder = mlb.fit(dataset.location[0]) #fit it with all the possible values of location 

In [12]:
dataset['location']= map(list, dataset.location)

In [23]:
dataset.location.apply(lambda x : [x]  ) #if isinstance(x,str) else x

0    [[NY, CA, MI]]
1              [CA]
2    [[NY, CA, MA]]
Name: location, dtype: object

In [44]:
locations =[]
for location in dataset.location:
    if isinstance(location , str):
        print location
        location = [location]
        locations.append(encoder.transform(location))
        print encoder.transform(location)
    else:
        print location
        locations.append(encoder.transform(location))
        print encoder.transform(location)

['NY', 'CA', 'MI']
[[0 0 1]
 [1 0 0]
 [0 1 0]]
CA
[[1 0 0]]
['NY', 'CA', 'MA']
[[0 0 1]
 [1 0 0]
 [0 0 0]]


In [28]:
dataset['location'] = locations

In [29]:
dataset

location                        menu price
0  [[0, 0, 1], [1, 0, 0], [0, 1, 0]]            [Italian, Greek]    $$
1                        [[1, 0, 0]]                  [Japanese]    $$
2  [[0, 0, 1], [1, 0, 0], [0, 0, 0]]  [Italian, Greek, Japanese]     $